version: "3"
services:
    www:
        build:
          context: ./apache-php
          args:
              - WITH_XDEBUG=false
        ports:
            - "8888:80"
        env_file: .env.docker
        # environment:
        #     XDEBUG_CONFIG: "remote_host=localhost remote_connect_back=1"
        #     PHP_IDE_CONFIG: "serverName=localhost"
        volumes:
            - ./:/var/www/html
        networks:
            - detector-network

    redis:
        image: redis:latest
        ports:
        - "6868:6379"
        volumes:
        - ./redis:/data
        networks:
            - detector-network

volumes:
    persistent:

networks:
    detector-network:
        driver: bridge
